services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fake
      - POSTGRES_DB=deno
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    ulimits:
      memlock:
        soft: -1
        hard: -1

  redis:
    image: redis:7
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=fake
      - REDIS_NAME=deno
    restart: on-failure
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - 6379:6379
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
